export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'

export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCTBYID = 'GET_PRODUCTBYID'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'